DO $$
BEGIN
  CREATE TYPE "AiProvider" AS ENUM (
    'OPENAI',
    'ANTHROPIC',
    'GOOGLE',
    'MISTRAL',
    'OPENROUTER',
    'DEEPSEEK'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "workspaces"
ADD COLUMN IF NOT EXISTS "aiProvider" "AiProvider" NOT NULL DEFAULT 'GOOGLE',
ADD COLUMN IF NOT EXISTS "aiModel" TEXT,
ADD COLUMN IF NOT EXISTS "custom_ai_key" TEXT,
ADD COLUMN IF NOT EXISTS "ai_usage_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "last_usage_reset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
